// the random quotes api: 

// https://api.api-ninjas.com/v1/quotes?category='categoryname'

// VITE_APP_RANDOM_USERS_API_KEY = 'sLMPkjpKJEaY4m4wUfuduA==jrkx9E4YMD8JkjaS'

// list of categories:

export const TopicArr = [
  "age",
  "alone",
  "amazing",
  "anger",
  "architecture",
  "art",
  "attitude",
  "beauty",
  "birthday",
  "business",
  "car",
  "change",
  "communications",
  "computers",
  "courage",
  "dad",
  "death",
  "design",
  "dreams",
  "education",
  "experience",
  "failure",
  "faith",
  "family",
  "famous",
  "fear",
  "fitness",
  "food",
  "forgiveness",
  "freedom",
  "friendship",
  "future",
  "good",
  "graduation",
  "great",
  "happiness",
  "health",
  "home",
  "imagination",
  "inspirational",
  "intelligence",
  "knowledge",
  "learning",
  "life",
  "medical",
  "money",
  "morning",
  "movies",
  "success",
];